[app]
# 事务 batch 数
# 用于数据写入 batch 提交事务数
insert-batch-size = 100
# 是否开启更新元数据 meta-schema 库表慢日志，单位毫秒
slowlog-threshold = 1024
# pprof 端口
pprof-port = ":9696"



[oracle]
username = "test"
password = "test"
host = "192.168.9.26"
port = 1521
schema-name = "test"
service-name = "ORCL"

# include-table 和 exclude-table 不能同时配置，两者只能配置一个,如果两个都没配置则 Schema 内表全迁移
# include-table 和 exclude-table 支持正则表达式以及通配符（tab_*/tab*）
include-table = []
exclude-table = ["TEST"]

[log]
# 日志 level
log-level = "info"
# 日志文件路径
log-file = "./gominerlog.log"
# 每个日志文件保存的最大尺寸 单位：M
max-size = 128
# 文件最多保存多少天
max-days = 7
# 日志文件最多保存多少个备份
max-backups = 30